<template>
  <div class="wrapper" ref="aaa">
    <ul class="cart">
      <li>费雷</li>
      <li>费雷</li>
      <li>费雷</li>
      <li>费雷</li>
      <li>费雷</li>
      <li>费雷</li>
      <li>费雷</li>
      <li>费雷</li>
      <li>费雷</li>
      <li>费雷</li>
      <li>费雷</li>
      <li>费雷</li>
      <li>费雷</li>
      <li>费雷</li>
      <li>费雷</li>
      <li>费雷</li>
      <li>费雷</li>
      <li>费雷</li>
      <li>费雷</li>
      <li>费雷</li>
      <li>费雷</li>
      <li>费雷</li>
      <li>费雷</li>
      <li>费雷</li>
      <li>费雷</li>
      <li>费雷</li>
      <li>费雷</li>
      <li>费雷</li>
      <li>费雷</li>
      <li>费雷</li>
      <li>费雷</li>
      <li>费雷</li>
      <li>费雷</li>
      <li>费雷</li>
      <li>费雷</li>
      <li>费雷</li>
      <li>费雷</li>
      <li>费雷</li>
      <li>费雷</li>
      <li>费雷</li>
      <li>费雷</li>
      <li>费雷</li>
      <li>费雷</li>
      <li>费雷</li>
      <li>费雷</li>
      <li>费雷</li>
      <li>费雷</li>
      <li>费雷</li>
      <li>费雷</li>
      <li>费雷</li>
      <li>费雷</li>
      <li>费雷</li>
      <li>费雷</li>
      <li>费雷</li>
      <li>费雷</li>
      <li>费雷</li>
      <li>费雷</li>
      <li>费雷</li>
      <li>费雷</li>
      <li>费雷</li>
      <li>费雷</li>
      <li>费雷</li>
      <li>费雷</li>
      <li>费雷</li>
      <li>费雷</li>
      <li>费雷</li>
      <li>费雷</li>
      <li>费雷</li>
      <li>费雷</li>
      <li>费雷</li>
      <li>费雷</li>
      <li>费雷</li>
      <li>费雷</li>
      <li>费雷</li>
      <li>费雷</li>
      <li>费雷</li>
      <li>费雷</li>
      <li>费雷</li>
      <li>费雷</li>
      <li>费雷</li>
      <li>费雷</li>
      <li>费雷</li>
      <li>费雷</li>
      <li>费雷</li>
      <li>费雷</li>
      <li>费雷</li>
      <li>费雷</li>
      <li>费雷</li>
      <li>费雷</li>
      <li>费雷</li>
      <li>费雷</li>
      <li>费雷</li>
      <li>费雷</li>
      <li>费雷</li>
      <li>费雷</li>
      <li>费雷</li>
      <li>费雷</li>
      <li>费雷</li>
      <li>费雷</li>
      <li>费雷</li>
      <li>费雷</li>
      <li>费雷</li>
      <li>费雷</li>
      <li>费雷</li>
      <li>费雷</li>
      <li>费雷</li>
      <li>费雷</li>
      <li>费雷</li>
      <li>费雷</li>
      <li>费雷</li>
      <li>费雷</li>
      <li>费雷</li>
      <li>费雷</li>
      <li>费雷</li>
      <li>费雷</li>
      <li>费雷</li>
      <li>费雷</li>
      <li>费雷</li>
      <li>费雷</li>
      <li>费雷</li>
      <li>费雷</li>
      <li>费雷</li>
      <li>费雷</li>
      <li>费雷</li>
      <li>费雷</li>
      <li>费雷</li>
      <li>费雷</li>
      <li>费雷</li>
      <li>费雷</li>
      <li>费雷</li>
      <li>费雷</li>
      <li>费雷</li>
      <li>费雷</li>
      <li>费雷</li>
      <li>费雷</li>
      <li>费雷</li>
      <li>费雷</li>
      <li>费雷</li>
      <li>费雷</li>
      <li>费雷</li>
      <li>费雷</li>
      <li>费雷</li>
      <li>费雷</li>
      <li>费雷</li>
      <li>费雷</li>
      <li>费雷</li>
      <li>费雷</li>
      <li>费雷</li>
      <li>费雷</li>
      <li>费雷</li>
      <li>费雷</li>
      <li>费雷</li>
      <li>费雷</li>
      <li>费雷</li>
      <li>费雷</li>
      <li>费雷</li>
      <li>费雷</li>
      <li>费雷</li>
      <li>费雷</li>
      <li>费雷</li>
      <li>费雷</li>
      <li>费雷</li>
      <li>费雷</li>
      <li>费雷</li>
      <li>费雷</li>
      <li>费雷</li>
      <li>费雷</li>
      <li>费雷</li>
      <li>费雷</li>
      <li>费雷</li>
      <li>费雷</li>
      <li>费雷</li>
      <li>费雷</li>
      <li>费雷</li>
      <li>费雷</li>
      <li>费雷</li>
      <li>费雷</li>
      <li>费雷</li>
      <li>费雷</li>
      <li>费雷</li>
      <li>费雷</li>
      <li>费雷</li>
      <li>费雷</li>
      <li>费雷</li>
      <li>费雷</li>
      <li>费雷</li>
      <li>费雷</li>
      <li>费雷</li>
      <li>费雷</li>
      <li>费雷</li>
      <li>费雷</li>
      <li>费雷</li>
      <li>费雷</li>
      <li>费雷</li>
      <li>费雷</li>
      <li>费雷</li>
      <li>费雷</li>
      <li>费雷</li>
      <li>费雷</li>
      <li>费雷</li>
      <li>费雷</li>
      <li>费雷</li>
      <li>费雷</li>
      <li>费雷</li>
      <li>费雷</li>
      <li>费雷</li>
      <li>费雷</li>
      <li>费雷</li>
      <li>费雷</li>
      <li>费雷</li>
      <li>费雷</li>
      <li>费雷</li>
      <li>费雷</li>
      <li>费雷</li>
      <li>费雷</li>
      <li>费雷</li>
      <li>费雷</li>
      <li>费雷</li>
      <li>费雷</li>
      <li>费雷</li>
      <li>费雷</li>
      <li>费雷</li>
      <li>费雷</li>
      <li>费雷</li>
      <li>费雷</li>
      <li>费雷</li>
      <li>费雷</li>
      <li>费雷</li>
      <li>费雷</li>
      <li>费雷</li>
      <li>费雷</li>
      <li>费雷</li>
      <li>费雷</li>
      <li>费雷</li>
      <li>费雷</li>
      <li>费雷</li>
      <li>费雷</li>
      <li>费雷</li>
      <li>费雷</li>
      <li>费雷</li>
      <li>费雷</li>
      <li>费雷</li>
      <li>费雷</li>
      <li>费雷</li>
      <li>费雷</li>
      <li>费雷</li>
      <li>费雷</li>
      <li>费雷</li>
      <li>费雷</li>
      <li>费雷</li>
      <li>费雷</li>
      <li>费雷</li>
      <li>费雷</li>
      <li>费雷</li>
      <li>费雷</li>
      <li>费雷</li>
      <li>费雷</li>
      <li>费雷</li>
      <li>费雷</li>
      <li>费雷</li>
      <li>费雷</li>
      <li>费雷</li>
      <li>费雷</li>
      <li>费雷</li>
      <li>费雷</li>
      <li>费雷</li>
      <li>费雷</li>
      <li>费雷</li>
      <li>费雷</li>
      <li>费雷</li>
      <li>费雷</li>
      <li>费雷</li>
      <li>费雷</li>
      <li>费雷</li>
      <li>费雷</li>
      <li>费雷</li>
      <li>费雷</li>
      <li>费雷</li>
      <li>费雷</li>
      <li>费雷</li>
      <li>费雷</li>
      <li>费雷</li>
      <li>费雷</li>
      <li>费雷</li>
      <li>费雷</li>
      <li>费雷</li>
      <li>费雷</li>
      <li>费雷</li>
      <li>费雷</li>
      <li>费雷</li>
      <li>费雷</li>
      <li>费雷</li>
      <li>费雷</li>
      <li>费雷</li>
      <li>费雷</li>
      <li>费雷</li>
      <li>费雷</li>
      <li>费雷</li>
      <li>费雷</li>
      <li>费雷</li>
      <li>费雷</li>
      <li>费雷</li>
      <li>费雷</li>
      <li>费雷</li>
      <li>费雷</li>
      <li>费雷</li>
      <li>费雷</li>
      <li>费雷</li>
      <li>费雷</li>
      <li>费雷</li>
      <li>费雷</li>
      <li>费雷</li>
    </ul>
  </div>
</template>

<script>
import BScroll from 'better-scroll';
export default {
  data(){
    return{
      scroll:null
    }
  },
  mounted(){
    //找到这个class标签使其有作用
 this.scroll= new BScroll(this.$refs.wrapper,{
    probeType:3,//这儿是监听滚动的距离的一种特性，侦测，0和1 都是 不侦测，3就是开始侦测
  //2是手指滚动的过程中检测，手指离开的时候不检测，
  //3是只要手指动了就会检测，
  click:true,
  pullUpLoad:true
    })
    this.scroll.on('scroll',(position)=>{
      console.log(position);
    })
    this.scroll.on('pullingUp',()=>{
      console.log('上拉打印更多');
    })
  }
}
</script>

<style scoped>
.wrapper{
  height:150px;
  background-color: brown;
  overflow: hidden;
  /* overflow-y: scroll; */
}
</style>